obj-$(CONFIG_FPGA_LED)			 += fpga_led.o
obj-$(CONFIG_FPGA_TEXT_LCD)		 += fpga_textlcd.o
obj-$(CONFIG_FPGA_SEGMENT)		 += fpga_segment.o
obj-$(CONFIG_FPGA_DIP_SWITCH)	 	 += fpga_dipsw.o
obj-$(CONFIG_FPGA_PIEZO)		 += fpga_piezo.o
obj-$(CONFIG_FPGA_FULL_COLOR_LED)	 += fpga_fullcolorled.o
obj-$(CONFIG_FPGA_OLED)			 += fpga_oled.o
obj-$(CONFIG_FPGA_DOT_MATRIX)		 += fpga_dotmatrix.o
